# -*- coding: utf-8 -*-
"""IDS_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12PVOz45fZsHuLKwsisRIX50mgz4QNKti
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

columns = [
"duration","protocol_type","service","flag","src_bytes","dst_bytes","land",
"wrong_fragment","urgent","hot","num_failed_logins","logged_in",
"num_compromised","root_shell","su_attempted","num_root","num_file_creations",
"num_shells","num_access_files","num_outbound_cmds","is_host_login",
"is_guest_login","count","srv_count","serror_rate","srv_serror_rate",
"rerror_rate","srv_rerror_rate","same_srv_rate","diff_srv_rate",
"srv_diff_host_rate","dst_host_count","dst_host_srv_count",
"dst_host_same_srv_rate","dst_host_diff_srv_rate",
"dst_host_same_src_port_rate","dst_host_srv_diff_host_rate",
"dst_host_serror_rate","dst_host_srv_serror_rate",
"dst_host_rerror_rate","dst_host_srv_rerror_rate","label","difficulty"
]
import pandas as pd

data = pd.read_csv("dataset.csv", names=columns)

print("Dataset Loaded Successfully")
print(data.head())

data = data.drop("difficulty", axis=1)

from sklearn.preprocessing import LabelEncoder

le_protocol = LabelEncoder()
le_service = LabelEncoder()
le_flag = LabelEncoder()
le_label = LabelEncoder()

data['protocol_type'] = le_protocol.fit_transform(data['protocol_type'])
data['service'] = le_service.fit_transform(data['service'])
data['flag'] = le_flag.fit_transform(data['flag'])

data['label'] = le_label.fit_transform(data['label'])

X = data.drop("label", axis=1)
y = data["label"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.model_selection import train_test_split

# Features (everything except label)
X = data.drop('label', axis=1)

# Target (attack type)
y = data['label']

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Dataset Split Completed")

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100)

model.fit(X_train, y_train)

print("Model Training Completed")

from sklearn.metrics import accuracy_score

predictions = model.predict(X_test)

accuracy = accuracy_score(y_test, predictions)

print("Model Accuracy:", accuracy)

sample = X_test.iloc[[0]]

prediction = model.predict(sample)

attack_type = le_label.inverse_transform(prediction)[0]

print("\n----- Intrusion Detection Result -----")

if attack_type == "normal":
    print("Traffic Status: Normal")
    print("Action: Connection Allowed")

else:
    print("Intrusion Detected!")
    print("Attack Type:", attack_type)
    print("Action: Blocking Connection")

attack_categories = {

# Normal
"normal": "Normal Traffic",

# DoS attacks
"neptune": "DoS",
"smurf": "DoS",
"back": "DoS",
"teardrop": "DoS",
"pod": "DoS",
"land": "DoS",

# Probe attacks
"satan": "Probe",
"ipsweep": "Probe",
"nmap": "Probe",
"portsweep": "Probe",
"mscan": "Probe",
"saint": "Probe",

# R2L attacks
"guess_passwd": "R2L",
"ftp_write": "R2L",
"imap": "R2L",
"phf": "R2L",
"multihop": "R2L",
"warezmaster": "R2L",
"warezclient": "R2L",

# U2R attacks
"buffer_overflow": "U2R",
"rootkit": "U2R",
"perl": "U2R",
"loadmodule": "U2R"
}

sample = X_test.iloc[[50]]

prediction = model.predict(sample)

attack_type = le_label.inverse_transform(prediction)[0]

print("\n----- Intrusion Detection Result -----")

if attack_type == "normal":

    print("Traffic Status: NORMAL")
    print("Category: Normal Traffic")
    print("Risk Level: LOW")
    print("Action: Connection Allowed")

else:

    category = attack_categories.get(attack_type, "Unknown")

    print("Intrusion Detected!")
    print("Attack Type:", attack_type)
    print("Category:", category)
    print("Risk Level: HIGH")
    print("Action: BLOCKED")